# Introduction


<!-- ## Need for management of short-lived / annual species -->


Under the Magnuson-Stevens Fishery Conservation and Management Act, NOAA Fisheries is mandated to facilitate the sustainable management of exploited fisheries, including short-lived species with complex dynamics.  A foundational component of this management is the development of robust, representative population models. However, typical population dynamics models used in stock assessments—such as age-structured and surplus production models—often perform poorly for short-lived species due to the disjointed relationship between stock size and recruitment as well as the violation of core model assumptions, such as catch rates reflecting abundance [@carruthers2014evaluating; @kokkalis2024good]. Because the carrying capacities of these species are highly sensitive to interannual environmental fluctuations, generating reliable benchmarks to track their sustainability status presents a significant challenge [@barnes1992recent; @jacobson2001surplus; @thiaw2009surplus].


<!-- Marine ecosystems are complex systems with many interacting components that are difficult to measure and predict.   -->


Short-lived species frequently exhibit non-equilibrium dynamics and nonlinear state-dependent behavior, making them particularly complex to model [@glaser_complex_2014; @fogarty_dynamic_2016]. Interactions that change over time and as a function of the system’s state—such as shifts in prevailing environmental conditions—must be captured at an appropriate spatiotemporal scale to detect and define a predictive relationship [@chang2020evaluation]. Similarly, short-lived species are often prey items for longer-lived species, introducing a set of predator species drivers with their own complex, state-dependent interactions. Empirical dynamic modeling (EDM) has proven successful at capturing these complexities by applying Takens' theorem of delay embedding [@takens_1981]. Through this approach, time lags of species abundance are used to reconstruct the full system dynamics based on information inherently encoded within the abundance time series. The empirical data need to be a sufficiently long consecutive time series to appropriately define the space and ultimately predict the next steps in the time series, with the option to apply a variable time step methodology [@johnson_empirical_2022]. To appropriately define the complexity of the system and embed the attractor, the embedding dimension should be greater than twice the number of drivers on the system.  A general rule of thumb for applying EDM is that the embedding dimension should also be less than the square root of the time series length, where time series length is typically the limiting factor in applying EDM to map population abundance [@munch_frequently_2020; @munch_recent_2022]. Ultimately, EDM eliminates the need to explicitly define all environmental drivers and mathematical relationships impacting abundance, and this approach was recently adapted to include fishery landings and estimate management benchmarks including Maximum Sustainable Yield (MSY) [@tsai_empirical_2024].  



<!-- ## Gulf shrimp fishery -->
The Gulf of America brown, pink, and white shrimp are prime candidates for EDM due to their oscillatory and highly variable population dynamics alongside the availability of a long-term fishery-independent survey measuring their abundance. The primary management measures affecting wild-caught Gulf brown shrimp include the Texas Closure and the Red Snapper Exclusion Zone.  The Texas Closure has occurred between approximately May 15-July 15 since 1981 in federal waters off Texas and is intended to allow shrimp to grow to higher value market categories before harvest.  The Red Snapper Exclusion Zone includes annual shrimping effort caps in the western Gulf from 10-30 fathoms and is intended to reduce shrimping effort and associated mortality in critical red snapper juvenile habitat.  Since this management was enacted in 2008, the trawl day threshold has incrementally increased twice, and the fishery has never been shut down due to this measure [@gallaway_changes_2020].  The trawl-day threshold is currently 33,124 trawl days, and the highest amount of effort in this zone was estimated as 31,458 in 2014 (Internal comm, K. Dettloff). Because 2014 is the closest effort has come to reaching the Red Snapper Exclusion Zone threshold since it was implemented in 2008, it will be used as a reference point for interpreting effort caps and future results. Considering 2014 as a broad management reference point here has many assumptions including simplifications across trawling effort and shrimp species population distribution in time and space. 


The Gulf shrimp fishery was once extremely profitable and remains one of the most valuable sources of landings in the United States [@asche_global_2022; @liese_etal_2026]. Shrimp is a highly desirable seafood product, leading in many nations' seafood consumption and aquaculture production [@gephart2024globalization]. The short lifespan and fast growth of shrimp make it an ideal species to farm for food [@rothlisberg1998aspects; @emerenciano2022intensification].  The global value of shrimp lured investors in aquaculture, who were able to trim down costs to produce shrimp and push prices to historic lows [@asche_us_2012]. The globalization of the shrimp market with a focus on cheap aquaculture has resulted in dire economic operating conditions for the US commercial fishery [@wp_socialdim]. While US shrimp prices are determined by the global market, there is some evidence for local supply shocks in short term prices [@asche2026impact]. Plummeting ex-vessel prices and increasing fuel costs have created a situation in which most vessels struggle to remain profitable. Further, Gulf shrimp vessels have endured increasing hurricane frequency and many have exited the fleet; those that remain may oscillate between narrowing profit margins and economic losses [@asche_global_2022; @liese_etal_2026].


Industry impacts of the US Gulf fleet were documented during stakeholder listening sessions held at the Gulf of America shrimp stock assessment Data Workshop and throughout coastal Gulf shrimping communities. During these sessions, it became clear that the economic hardship faced by the fishery transcends domestic fishery management solutions. The bulk of the problems are globally influenced, and the National Seafood Strategy is working to address these problems, informed by information gathered through the newly formed [Shrimp Futures Project](https://www.fisheries.noaa.gov/southeast/socioeconomics/shrimp-futures-initiative). 


<!-- ## Economic scenario projections -->

These conditions motivated us to simulate varying economic scenarios to identify conditions that may lead to improved revenue for the shrimp fleet and determine if there is a threshold beyond which the fishery risks overexploiting the stock. Strategies such as country-of-origin labeling in 2005 resulted in improvements to domestic product preference, signifying successful market segmentation [@asche_global_2022]. Further market segmentation can be realized through premium product labeling or certifications, where consumers are able to distinguish domestically sourced shrimp and are willing to pay more to support (often more costly) sustainable fishing practices [@brecard2009determinants; @roheim2011elusive]. Tariffs have been proposed to protect US domestic interests, and a new executive order cites Restoring American Seafood Competitiveness, where tariffs would affect both wild-caught and farmed imported shrimp. Here, we assume shrimp is an inelastic good, meaning US domestic shrimpers would pocket a significant share of the increase in price from tariffs, and consumers in the US would pay the additional premium [@asche_global_2022].  We investigated the impacts of successful implementation of premium-label marketing to yield a higher ex-vessel price for domestic products, implementation of tariffs, and continued competition with farmed imports to investigate the range of possible scenarios for the Gulf shrimp fishery. We paired each of these scenarios with a range of fuel prices to investigate the range of economic scenarios US shrimpers may face in the future. Our goal was to link ex-vessel prices and fuel costs to harvest rates in assessment models, allowing us to potentially improve the predictive capability of the models, as well as simulate various economic scenarios with real impacts across the landings and population. Our rationale was to investigate potential policies that aim to improve the economic conditions for the US Gulf shrimp fleet while describing the realized harvest rate and impacts to the population.



