

# Discussion

Management of short-lived species is challenging, and GP-EDM has been shown to capture brown shrimp population dynamics better than models constrained by more rigid assumptions [@sedar87]. The U.S. Gulf shrimp fishery has unique dynamics defined by fast-growth, nonlinear dynamics, and a steadily increasing import market. We have developed a flexible framework that accurately projects the population into the future and incorporates market conditions that drive harvest rates. This framework also allowed us to simulate a range of economic scenarios and view the implications for the fishery and brown shrimp population sustainability.  

<!-- ## Price projection scenarios -->

The ex-vessel price projection simulation resulted in increased revenue in the fishery up to \$`r round(pmod13[pmod13$scenario=='label.premium',]$rev_avg,0)` million per year under the premium-label scenario from \$`r round(pmod13[pmod13$scenario=='status.quo',]$rev_avg,0)` million under the baseline price scenario while holding fuel price constant. This annual increase of \$`r round(pmod13[pmod13$scenario=='label.premium',]$rev_avg,0)-round(pmod13[pmod13$scenario=='status.quo',]$rev_avg,0)` million would greatly improve conditions for the U.S. Gulf shrimp fleet and has a minimal impact on the brown shrimp population.  Gulf brown shrimp are a resilient stock in which the estimated MSY vastly exceeds what the fishery is harvesting today.  The U.S. shrimp fleet is stymied by a global aquaculture market fueled by cheap production.  If fuel prices decrease or ex-vessel prices are increased through premium labeling or tariffs, there would be a resulting increase in effort to take advantage of increased revenue.  Shrimpers have very narrow profit margins, so even slight improvements in profitability facilitate increased effort. This leads to a compounding effect on total fleet revenue: a higher price and increased landings.


Recent publications on the economic state of the fishery by @liese_etal_2026 have confirmed that the realized scenario was a further reduction in prices due to expanding aquaculture.  Shrimp prices have decreased from \$4.64 per pound in 2021, to \$3.41 in 2022, and \$2.50 in 2023.  As technology continues to advance, the aquaculture industry continues to marginally reduce costs, resulting in reduced global shrimp prices. There are further ethical concerns regarding the reported use of antibiotics and slave labor for some aquaculture imports, for which complete testing and monitoring are impossible [@das2014low; @al2026antimicrobials].  The Shrimp Futures program stemmed from the realization that U.S. domestic fishery management policies have minimal impact on the future resilience of the fleet itself and is working to find a solution to ensure the United States has a domestic shrimp fleet in 2050. The increased farming scenario paired with increased fuel costs described in this study leaves little room for the U.S. Gulf shrimp fleet to make ends meet.

Tariffs are meant to provide incentives to purchase domestically produced goods by applying an extra cost to import goods.  There has been national interest and uncertainty around tariffs in the U.S., and we used a 25\% tariff to approximate recent executive proposals.  In the case of U.S. domestic shrimp production, there is inherent value in national food security and supporting sustainable trawling practices that enforce bycatch reduction and turtle excluder devices.  Tariffs applied in this instance could force buyers to acknowledge the inherent value of domestic production described here.  Premium-label implementation could also facilitate an increase in ex-vessel prices for shrimpers, while shifting overhead costs to consumers.  Ultimately, for these projection scenarios to be realized, American consumers would need to decide that premium-priced domestic seafood production is worth the extra cost, both to support the sustainable fishing practices enforced by the U.S. and the security in maintaining food production for the nation.

<!-- ## Implications for the fishery -->

If the market conditions are improved for the Gulf shrimp fishery, the populations can almost certainly handle the level of increased exploitation.  Aquaculture can be beneficial to continue to feed nations, but the impacts on domestic profit margins have proven to be detrimental to the survival of this fishery. This work showed a range of possible economic scenarios for the shrimp fishery, under all of which the shrimp population remained stable. There are other fisheries management concerns around shrimp trawling including bycatch of finfish and endangered species. Red snapper juveniles are caught in shrimp trawls, which led to the 2008 implementation of the Red Snapper Exclusion Zone in the Western Gulf from 10-30 fathoms.  The current effort cap in this zone is 33,124 trawl days, and it was nearly hit in 2014 with 31,458 trawl days [@gallaway_changes_2020]. The peak harvest rate aggregated across sizes and seasons estimated here was 0.150 in 2014. The estimated harvest rate at MSY was estimated as 0.265, which exceeds the red snapper threshold, implying (with numerous simplifications across shrimp species, size class, time, and space) that the MSY threshold is not the limiting management constraint. Management actions related to bycatch that impact shrimp trawlers would need to be evaluated separately from this work, but a similar modeling framework could be developed to predict implications. 



EDM is a flexible data-driven modeling approach.  It has been shown to outperform traditional stock assessment models for short-lived species, which are predicated on rigid equilibrium assumptions.  In this publication, we displayed further adaptability, incorporating fuel and ex-vessel prices for both more accurate predictions of the population (for Large shrimp) and realistic market projection scenarios.  If this methodology is applied to a species with a more elastic market, an inverse demand function should be considered, where prices are expected to drop as landings increase [@asche2007studies]. This work resulted in strong predictive capability for brown shrimp abundance as well as the incorporation of realistic economic scenarios under future production.  


Future research includes exploring EDM for identifying high-productivity years in the Gulf with respect to shrimp biomass and further exploring environmental conditions in these years. We explored the inclusion of environmental covariates such as water temperature and salinity in the original EDM formulation, but focused on economic drivers for this study. @smith2017seafood found linkages between ex-vessel price of Large shrimp and hypoxia in the Gulf due to the decreased quantity of Large shrimp under these ecological conditions. With higher resolution effort data of the shrimp fleet available, these areas of study could be linked to better improve hypoxic zone prediction.

